### ISSUE TITLE
Bug with the navigation menu.

### ISSUE THREAD

**Issue by paolo754** [iqonicdesignofficial/hope-ui-vue-dashboard#1]
**Hello, I just found a bug:** The button to retract the navigation menu is invisible on the mobile version of HOPE UI Vue.js
Here is a screenshot: 

![IOS CAPTURE SAFARI](https://media.discordapp.net/attachments/658379511225909260/909134503283400844/IMG_2981.png?width=376&height=669)

I tested the dashboard on this site: https://hopeui-vue.pages.dev/

**Comment by chiragmistry007** [comment]
Hi there,
we have fixed this issue & also update our code. Please check our latest version.
[https://github.com/iqonicdesignofficial/hope-ui-vue-dashboard/releases/tag/v2.0.0](https://github.com/iqonicdesignofficial/hope-ui-vue-dashboard/releases/tag/v2.0.0)
